type nul >1.txt	
type nul >2.txt	
type nul >3.txt	
type nul >4.txt	
type nul >5.txt	
type nul >6.txt	
type nul >7.txt	
type nul >8.txt	
type nul >9.txt	
type nul >10.txt	
type nul >11.txt	
type nul >12.txt	
type nul >13.txt	
type nul >14.txt	
type nul >15.txt	
type nul >16.txt	
type nul >17.txt	
type nul >18.txt	
type nul >19.txt	
type nul >20.txt	
